## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("weather_data_cities.csv")
city_data_df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Weather Description
0,0,Dikson,73.5069,80.5464,30.79,97,100,13.69,RU,overcast clouds
1,1,Upernavik,72.7868,-56.1549,35.73,72,10,4.45,GL,clear sky
2,2,Georgetown,5.4112,100.3354,80.89,87,20,0.00,MY,few clouds
3,3,Egvekinot,66.3167,-179.1667,27.27,67,10,3.69,RU,clear sky
4,4,Mehamn,71.0357,27.8492,62.60,45,0,10.36,NO,clear sky

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 82
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Weather Description
19,19,Arraial Do Cabo,-22.9661,-42.0278,82.36,61,0,5.75,BR,clear sky
28,28,San Cristobal,7.7669,-72.2250,82.58,54,28,6.58,VE,scattered clouds
30,30,Kutum,14.2000,24.6667,88.70,13,100,16.58,SD,overcast clouds
37,37,Acapulco,16.8634,-99.8901,87.80,66,40,4.61,MX,scattered clouds
43,43,Butaritari,3.0707,172.7902,82.63,75,100,13.94,KI,overcast clouds
73,73,San Patricio,28.0170,-97.5169,85.01,61,100,12.71,US,overcast clouds
74,74,Bien Hoa,10.9500,106.8167,82.38,84,59,4.43,VN,broken clouds
82,82,Colon,9.3592,-79.9014,84.24,63,100,10.00,PA,overcast clouds
83,83,Bhola,22.6833,90.6500,83.64,84,5,10.51,BD,clear sky
86,86,Foam Lake,51.6500,-103.5343,86.02,33,7,4.90,CA,clear sky

In [5]:
# 4a. Determine if there are any empty rows. 
preferred_cities_df.notnull().sum()

Unnamed: 0             119
City                   119
Lat                    119
Lng                    119
Max Temp               119
Humidity               119
Cloudiness             119
Wind Speed             119
Country                119
Weather Description    119
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
# N/A There are no empty rows.

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Weather Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
19,Arraial Do Cabo,BR,82.36,clear sky,-22.9661,-42.0278,
28,San Cristobal,VE,82.58,scattered clouds,7.7669,-72.2250,
30,Kutum,SD,88.70,overcast clouds,14.2000,24.6667,
37,Acapulco,MX,87.80,scattered clouds,16.8634,-99.8901,
43,Butaritari,KI,82.63,overcast clouds,3.0707,172.7902,
73,San Patricio,US,85.01,overcast clouds,28.0170,-97.5169,
74,Bien Hoa,VN,82.38,broken clouds,10.9500,106.8167,
82,Colon,PA,84.24,overcast clouds,9.3592,-79.9014,
83,Bhola,BD,83.64,clear sky,22.6833,90.6500,
86,Foam Lake,CA,86.02,clear sky,51.6500,-103.5343,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"   

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try: 
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found...skipping")

Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping

In [9]:
hotel_df.head()

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
19,Arraial Do Cabo,BR,82.36,clear sky,-22.9661,-42.0278,Pousada Porto Praia
28,San Cristobal,VE,82.58,scattered clouds,7.7669,-72.2250,Posada Villaven C.A.
30,Kutum,SD,88.70,overcast clouds,14.2000,24.6667,Dibbo areaمنطقة دبو
37,Acapulco,MX,87.80,scattered clouds,16.8634,-99.8901,HS Hotsson Smart Acapulco
43,Butaritari,KI,82.63,overcast clouds,3.0707,172.7902,Isles Sunset Lodge

In [10]:
# 7. Drop the rows where there is no Hotel Name.
import numpy as np
hotel_df.replace('', np.nan, inplace=True)
hotel_df=hotel_df[pd.notnull(hotel_df['Hotel Name'])]

In [11]:
hotel_df.head(30)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
19,Arraial Do Cabo,BR,82.36,clear sky,-22.9661,-42.0278,Pousada Porto Praia
28,San Cristobal,VE,82.58,scattered clouds,7.7669,-72.2250,Posada Villaven C.A.
30,Kutum,SD,88.70,overcast clouds,14.2000,24.6667,Dibbo areaمنطقة دبو
37,Acapulco,MX,87.80,scattered clouds,16.8634,-99.8901,HS Hotsson Smart Acapulco
43,Butaritari,KI,82.63,overcast clouds,3.0707,172.7902,Isles Sunset Lodge
73,San Patricio,US,85.01,overcast clouds,28.0170,-97.5169,"Motel 6 Sinton, TX"
74,Bien Hoa,VN,82.38,broken clouds,10.9500,106.8167,OYO 991 Duy Anh Hotel
82,Colon,PA,84.24,overcast clouds,9.3592,-79.9014,Sand Diamond Hotel
83,Bhola,BD,83.64,clear sky,22.6833,90.6500,Student Hostel (Shahbaz Khan Hostel)
86,Foam Lake,CA,86.02,clear sky,51.6500,-103.5343,Fishing Lake Lodge LTD
93,Champerico,GT,89.60,scattered clouds,14.3000,-91.9167,"Hotel y restaurante ""El Diamante"""
118,Itarema,BR,82.35,few clouds,-2.9248,-39.9167,"Sea Lounge! Bar, Club & Restaurant"
125,Jose Bonifacio,BR,88.86,clear sky,-21.0528,-49.6883,HOTEL DOS VIAJANTES
129,Madras,IN,85.96,few clouds,13.0878,80.2785,City home
140,Aden,YE,88.21,overcast clouds,12.7794,45.0367,Sama Emirate Hotel
157,Touros,BR,83.30,clear sky,-5.1989,-35.4608,INN NEW HORIZON
159,Umm Lajj,SA,84.33,clear sky,25.0213,37.2685,Moon light Furnished Units
170,Resistencia,AR,82.06,clear sky,-27.4606,-58.9839,Niyat Urban Hotel
173,Hithadhoo,MV,83.59,overcast clouds,-0.6000,73.0833,Scoop Guest House
177,Tautira,PF,84.22,light rain,-17.7333,-149.1500,Pension Oaoa
189,Edgewater,US,86.18,light rain,28.9889,-80.9023,Islander Beach Resort
195,Vung Tau,VN,83.03,broken clouds,10.3460,107.0843,Green hotel
202,Saint-Georges,GD,85.68,few clouds,12.0564,-61.7485,Radisson Grenada Beach Resort
208,Oriximina,BR,88.45,moderate rain,-1.7656,-55.8661,Pousada Tia Amélia
222,Caucaia,BR,86.00,clear sky,-3.7361,-38.6531,M.O.S. Logística - Filial Fortaleza
223,Hun,LY,89.73,broken clouds,29.1268,15.9477,Alrwasi Hotel
224,Pitimbu,BR,82.99,scattered clouds,-7.4706,-34.8086,Reserva do Abiaí
240,Gaoual,GN,83.01,broken clouds,11.7500,-13.2000,Hotel koliba
241,Phalodi,IN,86.07,broken clouds,27.1333,72.3667,"HOTEL NEW GOLDEN PALACE , PHALODI"
244,Turbat,PK,84.65,clear sky,26.0023,63.0440,Mubashar Quarters

In [12]:
# 8a. Create the output File (CSV)

# 8b. Export the City_Data into a csv
hotel_df.to_csv('WeatherPy_vacation.csv')

In [13]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Weather Description</dt><dd>{Weather Description}</dd>
</dl>

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [15]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))